name: Build driver solution
on:
  push:

jobs:
  build-sensors-combo-driver:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2022
    # env:
    #   Solution_Path: FrameworkSensors\FrameworkSensors.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # msbuild ${{ env.Solution_Path }} -p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}
      - name: Build solution
        run: |
          msbuild FrameworkSensors\FrameworkSensors.sln /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      # Can EV sign (have to replace existing signatures)
      # java -jar ~/Downloads/jsign-7.1.jar --replace --storetype PIV --storepass ****** --tsaurl http://ts.ssl.com --tsmode RFC3161 \
      #   FrameworkSensors.dll
      # java -jar ~/Downloads/jsign-7.1.jar --replace --storetype PIV --storepass ****** --tsaurl http://ts.ssl.com --tsmode RFC3161 \
      #   FrameworkSensors.cat
      - name: Create bundle
        run: |
          mkdir bundle
          cp FrameworkSensors\x64\${{ matrix.configuration }}\FrameworkSensors\FrameworkSensors.cat bundle\
          cp FrameworkSensors\x64\${{ matrix.configuration }}\FrameworkSensors\FrameworkSensors.dll bundle\
          cp FrameworkSensors\x64\${{ matrix.configuration }}\FrameworkSensors\FrameworkSensors.inf bundle\
          cp FrameworkSensors\x64\${{ matrix.configuration }}\FrameworkSensors.pdb bundle\

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: framework_win_sensors_${{ matrix.configuration }}
          path: bundle
